# 02 — Aggregate · Annotate · Normalize · FeatureSelect (MERGED)

> Versão • 2026-04-23 13:25

Notebook **unificado**: permite construir o dataset a partir de **SQLite** (Per_* tables) **ou** de **CSVs por compartimento** (Cells/Cytoplasm/Nuclei).

Principais pontos:
- Preserva e padroniza **metadados** (`Metadata_Plate`, `Metadata_Well`, `Metadata_Site`).
- Prefixa *features* por compartimento.
- Agrega por **poço** (mediana).
- Anota por **platemap** (index flexível).
- Normaliza *plate-wise* (`mad_robustize`) com `pycytominer` (modo `all` ou `negcon`).
- Seleção de *features* com `FeatureSelect`.

## Passo 1 — Configuração do experimento

In [13]:
from __future__ import annotations

# Standard library
import re
import sqlite3
import string
from pathlib import Path
from typing import Optional

# Third-party
import numpy as np
import pandas as pd
from pycytominer import normalize as pc_normalize
from pycytominer.cyto_utils import infer_cp_features

# Pycytominer feature_select (API funcional preferível; fallback para versões antigas)
try:
    from pycytominer import feature_select as pc_feature_select  # functional API

    _FEATURESELECT_MODE = "functional"
except Exception:
    from pycytominer.operations import feature_select as _fs_mod  # legacy API

    PCFeatureSelect = _fs_mod.FeatureSelect
    _FEATURESELECT_MODE = "class"

# Display settings
pd.set_option("display.max_columns", 200)

## Passo 2 — Funções auxiliares

In [14]:
def find_repo_root(
    start: Path, markers=(".git", "pyproject.toml", "pixi.toml")
) -> Path:
    start = start.resolve()
    for p in (start, *start.parents):
        if any((p / m).exists() for m in markers):
            return p
    # fallback: sobe até 5 níveis (evita travar), mas melhor ter marker no repo
    return start.parents[5] if len(start.parents) > 5 else start


# Em VS Code, normalmente cwd == pasta do notebook
NOTEBOOK_DIR = Path.cwd().resolve()

REPO_ROOT = find_repo_root(NOTEBOOK_DIR)

In [15]:
# =========================================================
# Contexto do notebook / experimento
# =========================================================
NOTEBOOK_DIR = Path.cwd().resolve()
EXPERIMENT_ID = NOTEBOOK_DIR.name  # ex.: "7_dias"

# =========================================================
# Pastas “canônicas” do repositório
# (todas as outras rotas derivam daqui)
# =========================================================
WORKSPACE_DIR = REPO_ROOT / "workspace"

# =========================================================
# Pastas por área do workflow (sempre por EXPERIMENT_ID)
# =========================================================
METADATA_DIR = WORKSPACE_DIR / "metadata" / EXPERIMENT_ID
ANALYSIS_DIR = WORKSPACE_DIR / "analysis" / EXPERIMENT_ID
PROFILES_DIR = WORKSPACE_DIR / "profiles" / EXPERIMENT_ID

# =========================================================
# Subpastas padrão de outputs / figures
# (padroniza para não misturar arquivos na raiz do experimento)
# =========================================================
ANALYSIS_OUT_DIR = ANALYSIS_DIR / "outputs"
PROFILES_OUT_DIR = PROFILES_DIR / "outputs"
FIGS_DIR = PROFILES_DIR / "figs"
CACHE_DIR = PROFILES_OUT_DIR / "cache"

# =========================================================
# Arquivos de metadata (sempre dentro de METADATA_DIR)
# =========================================================
BARCODE_PLATEMAP_CSV = METADATA_DIR / "barcode_platemap.csv"
PLATEMAP_DIR = METADATA_DIR / "platemap"

# =========================================================
# Inputs do Jupyter 2
# (saída do Jupyter 1 / etapa anterior)
# =========================================================
INPUT_CSV = ANALYSIS_OUT_DIR / "single_cell_profiles.csv"

# =========================================================
# Checkpoints / caches do Jupyter 2
# (artefatos intermediários desta etapa)
# =========================================================
SINGLE_CELL_LOADED_PARQUET = CACHE_DIR / "single_cell_loaded.parquet"
SINGLE_CELL_ANNOTATED_PARQUET = CACHE_DIR / "single_cell_annotated.parquet"
SINGLE_CELL_READY_PARQUET = CACHE_DIR / "single_cell_ready.parquet"
PER_WELL_AGGREGATED_PARQUET = CACHE_DIR / "per_well_aggregated.parquet"
PER_WELL_NORMALIZED_PARQUET = CACHE_DIR / "per_well_normalized.parquet"

# =========================================================
# Outputs do Jupyter 2
# (artefatos gerados nesta etapa)
# =========================================================
PER_WELL_FEATURES_SELECTED_PARQUET = (
    PROFILES_OUT_DIR / "per_well_features_selected.parquet"
)

# =========================================================
# Garantir que pastas de saída existem
# =========================================================
for d in [ANALYSIS_OUT_DIR, PROFILES_OUT_DIR, FIGS_DIR, CACHE_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# =========================================================
# Checagens rápidas (fail fast)
# =========================================================
assert METADATA_DIR.exists(), f"METADATA_DIR não existe: {METADATA_DIR}"
assert BARCODE_PLATEMAP_CSV.exists(), f"Não achei: {BARCODE_PLATEMAP_CSV}"
assert PLATEMAP_DIR.exists(), f"PLATEMAP_DIR não existe: {PLATEMAP_DIR}"
assert INPUT_CSV.exists(), f"Não achei INPUT_CSV: {INPUT_CSV}"

In [16]:
def _status(exists: bool | None) -> str:
    return "—" if exists is None else ("✅ existe" if exists else "❌ não existe")


def row(label: str, value, exists: bool | None = None) -> None:
    # value pode ser Path ou str
    if isinstance(value, Path):
        v = str(value)
        e = value.exists() if exists is None else exists
    else:
        v = str(value)
        e = exists  # para strings, geralmente None

    print(f"{label:<20} {_status(e):<12} {v}")


# Agora imprime tudo em 1 linha, incluindo EXPERIMENT_ID
row("EXPERIMENT_ID", EXPERIMENT_ID)
row("NOTEBOOK_DIR", NOTEBOOK_DIR)
row("REPO_ROOT", REPO_ROOT)
row("METADATA_DIR", METADATA_DIR)
row("BARCODE_PLATE", BARCODE_PLATEMAP_CSV)
row("PLATEMAP_DIR", PLATEMAP_DIR)
row("INPUT_CSV", INPUT_CSV)
row("OUTPUT_PARQUET:", PER_WELL_FEATURES_SELECTED_PARQUET)

EXPERIMENT_ID        —            2026_04_Huh7_NPPS_24h
NOTEBOOK_DIR         ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/analysis/2026_04_Huh7_NPPS_24h
REPO_ROOT            ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7
METADATA_DIR         ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h
BARCODE_PLATE        ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h/barcode_platemap.csv
PLATEMAP_DIR         ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h/platemap
INPUT_CSV            ✅ existe     /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/analysis/2026_04_Huh7_NPPS_24h/outputs/single_cell_profiles.csv
OUTPUT_PARQUET:      ❌ não existe /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/per_well_features_selected.parquet

In [17]:
def _norm_well(x: str) -> str:
    """Normaliza poços para o formato A01–H12."""
    s = str(x).strip().upper()
    import re as _re

    m = _re.match(r"^([A-H])0?([1-9]|1[0-2])$", s)
    return f"{m.group(1)}{int(m.group(2)):02d}" if m else s


def ensure_core_metadata(
    df: pd.DataFrame, plate_value: Optional[str] = None
) -> pd.DataFrame:
    """
    Padroniza colunas de metadados sem remover nada.
    - Renomeia variações comuns -> Metadata_Plate/Well/Site
    - Normaliza Metadata_Well (A01–H12)
    """
    rename_map = {
        "Image_Metadata_Plate": "Metadata_Plate",
        "Image_Metadata_Well": "Metadata_Well",
        "Image_Metadata_Site": "Metadata_Site",
        "Site": "Metadata_Site",
        # variações ocasionais
        "Metadata_WellID": "Metadata_Well",
        "Well": "Metadata_Well",
        "Plate": "Metadata_Plate",
    }
    cols_to_rename = {k: v for k, v in rename_map.items() if k in df.columns}
    if cols_to_rename:
        df = df.rename(columns=cols_to_rename)
    if "Metadata_Plate" not in df.columns and plate_value is not None:
        df["Metadata_Plate"] = plate_value
    if "Metadata_Well" in df.columns:
        df["Metadata_Well"] = df["Metadata_Well"].map(_norm_well)
    return df


def dedupe_meta(df: pd.DataFrame) -> pd.DataFrame:
    """Remove duplicatas e faz 'coalesce' de Metadata_* (ex.: _x/_y), mantendo meta no início."""
    META_KEYS = ["Metadata_Plate", "Metadata_Well", "Metadata_Site"]
    df = df.loc[:, ~df.columns.duplicated()].copy()
    for k in META_KEYS:
        cols = [c for c in df.columns if c == k or c.startswith(k + "_")]
        if len(cols) > 1:
            base = cols[0]
            for extra in cols[1:]:
                df[base] = df[base].where(df[base].notna(), df[extra])
            for extra in cols[1:]:
                if extra in df.columns:
                    df.drop(columns=extra, inplace=True)
    meta_first = [c for c in META_KEYS if c in df.columns]
    return df[meta_first + [c for c in df.columns if c not in meta_first]]

## Passo 3 — Carregar ou retomar análise

In [ ]:
# Carrega artefatos auxiliares, se existirem
if PER_WELL_AGGREGATED_PARQUET.exists():
    df_agg = pd.read_parquet(PER_WELL_AGGREGATED_PARQUET)
    print("Também carregado df_agg:", df_agg.shape)

if PER_WELL_NORMALIZED_PARQUET.exists():
    df_norm = pd.read_parquet(PER_WELL_NORMALIZED_PARQUET)
    print("Também carregado df_norm:", df_norm.shape)

if PER_WELL_FEATURES_SELECTED_PARQUET.exists():
    df_fs = pd.read_parquet(PER_WELL_FEATURES_SELECTED_PARQUET)
    print("Também carregado df_fs:", df_fs.shape)

In [20]:
# =========================================================
# Retomar execução a partir do checkpoint mais avançado
# =========================================================
# Rode esta célula depois de:
# 1) imports
# 2) paths/configuração do experimento
# 3) funções auxiliares básicas
#
# Depois, continue a partir do passo indicado no print.
# =========================================================

if PER_WELL_FEATURES_SELECTED_PARQUET.exists():
    df_fs = pd.read_parquet(PER_WELL_FEATURES_SELECTED_PARQUET)
    print("✅ Checkpoint encontrado: Passo 8 — feature selection final")
    print("Retomando de df_fs:", df_fs.shape)
    print("➡️ Continue no Passo 9 — salvar/verificar artefatos finais.")

elif PER_WELL_NORMALIZED_PARQUET.exists():
    df_norm = pd.read_parquet(PER_WELL_NORMALIZED_PARQUET)
    print("✅ Checkpoint encontrado: Passo 7 — per-well normalizado")
    print("Retomando de df_norm:", df_norm.shape)
    print("➡️ Continue no Passo 8 — feature selection.")

elif PER_WELL_AGGREGATED_PARQUET.exists():
    df_agg = pd.read_parquet(PER_WELL_AGGREGATED_PARQUET)
    print("✅ Checkpoint encontrado: Passo 6 — per-well agregado")
    print("Retomando de df_agg:", df_agg.shape)
    print("➡️ Continue no Passo 7 — normalização.")

elif SINGLE_CELL_READY_PARQUET.exists():
    df_annot_ready = pd.read_parquet(SINGLE_CELL_READY_PARQUET)
    print("✅ Checkpoint encontrado: Passo 5 — single-cell anotado e limpo")
    print("Retomando de df_annot_ready:", df_annot_ready.shape)
    print("➡️ Continue no Passo 6 — agregação por poço.")

elif SINGLE_CELL_ANNOTATED_PARQUET.exists():
    df_annot = pd.read_parquet(SINGLE_CELL_ANNOTATED_PARQUET)
    print("✅ Checkpoint encontrado: Passo 4 — single-cell anotado")
    print("Retomando de df_annot:", df_annot.shape)
    print("➡️ Continue no Passo 5 — QC/limpeza antes da agregação.")

elif SINGLE_CELL_LOADED_PARQUET.exists():
    df = pd.read_parquet(SINGLE_CELL_LOADED_PARQUET)
    print("✅ Checkpoint encontrado: Passo 3 — single-cell carregado")
    print("Retomando de df:", df.shape)
    print("➡️ Continue no Passo 4 — anotação com platemap.")

else:
    df = pd.read_csv(INPUT_CSV, low_memory=False)
    df = ensure_core_metadata(df)
    df = dedupe_meta(df)
    df.to_parquet(SINGLE_CELL_LOADED_PARQUET, index=False)

    print("⚠️ Nenhum checkpoint encontrado.")
    print("CSV carregado e checkpoint criado.")
    print("df:", df.shape)
    print("➡️ Continue no Passo 4 — anotação com platemap.")

✅ Checkpoint encontrado: Passo 3 — single-cell carregado
Retomando de df: (113108, 1811)
➡️ Continue no Passo 4 — anotação com platemap.

## Passo 4 — Anotar com platemap
Seu barcode_platemap. csv deve mapear placa → arquivo de layout (ex.: layout _day1. csv). A função abaixo normaliza para colunas padrão: Metadata_Plate, filename, plate_map_name.

In [21]:
def read_barcode_platemap(index_csv: Path) -> pd.DataFrame:
    idx = pd.read_csv(index_csv)
    # mapeia nomes comuns -> padrão
    rename_map = {
        "Assay_Plate_Barcode": "Metadata_Plate",
        "Plate_Map_Name": "filename",
    }
    for k, v in rename_map.items():
        if k in idx.columns and v not in idx.columns:
            idx = idx.rename(columns={k: v})

    # se veio com outros nomes, tente deduzir
    if "Metadata_Plate" not in idx.columns:
        # tenta colunas candidatas
        for cand in ["Plate_Barcode", "Plate", "Barcode"]:
            if cand in idx.columns:
                idx = idx.rename(columns={cand: "Metadata_Plate"})
                break
    if "filename" not in idx.columns:
        for cand in ["Layout_File", "Platemap", "Plate_Map", "Plate_Map_Name"]:
            if cand in idx.columns:
                idx = idx.rename(columns={cand: "filename"})
                break

    # cria plate_map_name (nome sem .csv)
    if "plate_map_name" not in idx.columns and "filename" in idx.columns:
        idx["plate_map_name"] = (
            idx["filename"].astype(str).str.replace(".csv", "", regex=False)
        )

    # checagem mínima
    assert {"Metadata_Plate", "filename"}.issubset(
        idx.columns
    ), "barcode_platemap.csv precisa ter: Metadata_Plate, filename (e opcional plate_map_name)."

    # limpeza leve
    idx["filename"] = idx["filename"].astype(str).str.strip()
    idx["Metadata_Plate"] = idx["Metadata_Plate"].astype(str).str.strip()
    return idx


idx = read_barcode_platemap(BARCODE_PLATEMAP_CSV)
display(idx.head())

# Sanity-check: os arquivos existem na pasta metadado/platemap?
for fn in idx["filename"].unique():
    p = PLATEMAP_DIR / fn
    print(f"{fn}: existe? {p.exists()}  -> {p}")

             Metadata_Plate         filename plate_map_name
0  260221_171841_Plate_1_R1  layout_day1.csv    layout_day1
1  260223_170756_Plate_1_R2  layout_day2.csv    layout_day2
2  260228_135225_Plate_1_R3  layout_day3.csv    layout_day3

layout_day1.csv: existe? True  -> /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h/platemap/layout_day1.csv
layout_day2.csv: existe? True  -> /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h/platemap/layout_day2.csv
layout_day3.csv: existe? True  -> /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/metadata/2026_04_Huh7_NPPS_24h/platemap/layout_day3.csv

### 4.1 Ler cada layout de metadado/platemap/ e anotar por placa
Detectamos a coluna que contém poços (ex.: Well, Metadata_Well, well_id…), renomeamos para Metadata_Well, normalizamos para A01–H12 e fazemos merge com df por Metadata_Well (por placa).

In [22]:
def _read_platemap_csv(csv_path: Path) -> pd.DataFrame:
    """
    Lê um layout padronizado com colunas:
    [plate_map_name, well_position, Cell_Type, Treatment, Concentration, Control_Type]

    - Renomeia well_position -> Metadata_Well (normalizado A01–H12)
    - Mantém as colunas originais
    - Cria colunas auxiliares Metadata_* usadas em etapas posteriores (opcional, mas útil)
    """
    pm = pd.read_csv(csv_path)

    required = [
        "plate_map_name",
        "well_position",
        "Cell_Type",
        "Treatment",
        "Concentration",
        "Control_Type",
    ]
    missing = [c for c in required if c not in pm.columns]
    if missing:
        raise KeyError(
            f"{csv_path.name} não segue o padrão. Faltam colunas: {missing}. "
            f"Esperado: {required}"
        )

    # poço padronizado para A01–H12
    pm = pm.rename(columns={"well_position": "Metadata_Well"})
    pm["Metadata_Well"] = pm["Metadata_Well"].astype(str).map(_norm_well)

    # cria aliases Metadata_* que muitas rotinas usam
    pm["Metadata_Control_Type"] = pm["Control_Type"].astype(str).str.strip().str.lower()
    pm["Metadata_Treatment"] = pm["Treatment"]
    pm["Metadata_Concentration"] = pm["Concentration"]
    pm["Metadata_Cell_Type"] = pm["Cell_Type"]
    
    # limpeza leve
    pm["plate_map_name"] = pm["plate_map_name"].astype(str).str.strip()

    return pm


def annotate_per_plate(
    df_profiles: pd.DataFrame, idx: pd.DataFrame, pm_dir: Path
) -> pd.DataFrame:
    """
    Junta perfis (por placa) com o layout correspondente.
    O índice (barcode_platemap.csv) deve ter colunas: Metadata_Plate, filename, plate_map_name
    E cada layout_day*.csv deve seguir o padrão fixo acima.
    """
    outs = []
    for plate, sub in df_profiles.groupby("Metadata_Plate", sort=False):
        row = idx.loc[idx["Metadata_Plate"] == plate]
        if row.empty:
            print(
                f"⚠️ {plate}: placa não listada em barcode_platemap.csv — mantendo sem anotação"
            )
            outs.append(sub)
            continue

        pm_file = row["filename"].iloc[0]
        pm_name_from_index = (
            row["plate_map_name"].iloc[0] if "plate_map_name" in row.columns else None
        )

        pm_path = pm_dir / pm_file
        if not pm_path.exists():
            print(
                f"⚠️ {plate}: layout não encontrado: {pm_path} — mantendo sem anotação"
            )
            outs.append(sub)
            continue

        pm = _read_platemap_csv(pm_path)

        # Se o index define um nome-canônico da placa, sobrescreve para consistência
        if pm_name_from_index is not None:
            pm["plate_map_name"] = pm_name_from_index

        # merge por poço (padronizado)
        merged = sub.merge(pm, on="Metadata_Well", how="left")
        outs.append(merged)
        print(f"✓ {plate}: anotado via {pm_file} — shape {merged.shape}")

    return pd.concat(outs, axis=0, ignore_index=True)

### 4.2 Harmonizar nomes de colunas de anotação → Metadata_*

Se o seu layout contém Control_Type, Treatment, Concentration, etc., criamos colunas espelho Metadata_* para facilitar normalização e filtros.

In [23]:
df_annot = annotate_per_plate(df, idx, PLATEMAP_DIR)
df_annot = dedupe_meta(df_annot)

display(
    df_annot[
        [
            c
            for c in [
                "Metadata_Plate",
                "Metadata_Well",
                "plate_map_name",
                "Control_Type",
                "Metadata_Control_Type",
            ]
            if c in df_annot.columns
        ]
    ].head()
)

✓ 260221_171841_Plate_1_R1: anotado via layout_day1.csv — shape (33841, 1820)
✓ 260223_170756_Plate_1_R2: anotado via layout_day2.csv — shape (35309, 1820)
✓ 260228_135225_Plate_1_R3: anotado via layout_day3.csv — shape (37459, 1820)

,Metadata_Plate,Metadata_Well,plate_map_name,Control_Type,Metadata_Control_Type
0,260221_171841_Plate_1_R1,B10,layout_day1,negcon,negcon
1,260221_171841_Plate_1_R1,B10,layout_day1,negcon,negcon
2,260221_171841_Plate_1_R1,B10,layout_day1,negcon,negcon
3,260221_171841_Plate_1_R1,B10,layout_day1,negcon,negcon
4,260221_171841_Plate_1_R1,B10,layout_day1,negcon,negcon

In [24]:
df_annot.to_parquet(SINGLE_CELL_ANNOTATED_PARQUET, index=False)
print("Checkpoint salvo:", SINGLE_CELL_ANNOTATED_PARQUET)

Checkpoint salvo: /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/single_cell_annotated.parquet

> **Nota de limpeza do fluxo**  
> As células que tentavam reconstruir `df_annot` a partir de `df`, `df_agg` ou de aliases recriados manualmente foram removidas.  
> A partir daqui, o notebook assume **um único caminho**: carregar `df` → anotar com `annotate_per_plate()` → validar/limpar → agregar.

In [25]:
def compare_layout_vs_data(df_annot: pd.DataFrame, idx: pd.DataFrame, platemap_dir: Path):
    reports = {}
    for plate in sorted(df_annot["Metadata_Plate"].dropna().astype(str).unique()):
        row = idx.loc[idx["Metadata_Plate"].astype(str) == plate]
        if row.empty:
            reports[plate] = pd.DataFrame(
                {"info": [f"{plate}: não está em barcode_platemap.csv"]}
            )
            continue

        layout_file = platemap_dir / row["filename"].iloc[0]
        if not layout_file.exists():
            reports[plate] = pd.DataFrame(
                {"info": [f"{plate}: layout não encontrado: {layout_file.name}"]}
            )
            continue

        pm = _read_platemap_csv(layout_file)
        wells_layout = set(pm["Metadata_Well"].astype(str).map(_norm_well))
        wells_data = set(
            df_annot.loc[df_annot["Metadata_Plate"].astype(str) == plate, "Metadata_Well"]
            .astype(str)
            .map(_norm_well)
        )
        missing_in_layout = sorted(wells_data - wells_layout)
        reports[plate] = pd.DataFrame({"Metadata_Well": missing_in_layout})
    return reports


layout_gaps = compare_layout_vs_data(df_annot, idx, PLATEMAP_DIR)
for plate, rep in layout_gaps.items():
    print(f"\n== {plate} ==")
    display(rep.head(20))
    if "Metadata_Well" in rep.columns:
        print(f"Total faltando no layout: {len(rep)}")

== 260221_171841_Plate_1_R1 ==

Empty DataFrame
Columns: [Metadata_Well]
Index: []

Total faltando no layout: 0

== 260223_170756_Plate_1_R2 ==

Empty DataFrame
Columns: [Metadata_Well]
Index: []

Total faltando no layout: 0

== 260228_135225_Plate_1_R3 ==

Empty DataFrame
Columns: [Metadata_Well]
Index: []

Total faltando no layout: 0

## Passo 5 — QC e limpeza antes da agregação

Primeiro removemos poços que aparecem nos dados, mas **não existem no layout**.  
Depois, opcionalmente, removemos **poços técnicos específicos** definidos manualmente.  
O resultado dessa etapa será `df_annot_ready`, que é a base usada para a agregação.

In [26]:
# 1) montar um DF com todos os (plate, well) faltantes
missing_pairs = []
for plate, rep in layout_gaps.items():
    if isinstance(rep, pd.DataFrame) and "Metadata_Well" in rep.columns:
        for w in rep["Metadata_Well"].dropna().astype(str):
            missing_pairs.append((plate, _norm_well(w)))

missing_df = pd.DataFrame(missing_pairs, columns=["Metadata_Plate", "Metadata_Well"])
if not missing_df.empty:
    missing_df["Metadata_Well"] = missing_df["Metadata_Well"].map(_norm_well)

# 2) normalizar wells no df_annot e fazer anti-join (remover)
df_tmp = df_annot.copy()
df_tmp["__well_norm__"] = df_tmp["Metadata_Well"].astype(str).map(_norm_well)

if missing_df.empty:
    to_drop = pd.Series(False, index=df_tmp.index)
else:
    to_drop = (
        df_tmp[["Metadata_Plate", "__well_norm__"]]
        .merge(
            missing_df.rename(columns={"Metadata_Well": "__well_norm__"}).drop_duplicates(),
            how="left",
            on=["Metadata_Plate", "__well_norm__"],
            indicator=True,
        )["_merge"]
        .eq("both")
    )

n_removed = int(to_drop.sum())
print(f"🧹 Removendo {n_removed} linhas que não existem no layout.")

df_annot_clean = df_tmp.loc[~to_drop].drop(columns="__well_norm__").copy()
print("df_annot_clean shape:", df_annot_clean.shape)

🧹 Removendo 0 linhas que não existem no layout.
df_annot_clean shape: (106609, 1820)

In [27]:
rem_counts = (
    df_tmp.loc[to_drop, ["Metadata_Plate"]].value_counts().rename("removed").to_frame()
)
print(rem_counts.head(20) if not rem_counts.empty else "Nenhuma linha removida por ausência no layout.")

Nenhuma linha removida por ausência no layout.

In [28]:
import re

# helper: normaliza A1 -> A01
_well_re = re.compile(r"^\s*([A-Za-z])\s*0*([0-9]{1,2})\s*$")


def norm_well(s):
    s = str(s).strip()
    m = _well_re.match(s)
    if m:
        return f"{m.group(1).upper()}{int(m.group(2)):02d}"
    if len(s) >= 2 and s[0].isalpha() and s[1:].isdigit():
        return s[0].upper() + s[1:].zfill(2)
    return s


# poços a excluir (ajuste conforme necessário)
EXCLUDE_WELLS = {
    "250704_104743_Plate_1": ["B02"],
    "250709_095049_Plate_1": [
        "B03",
        "B11",
        "C03",
        "C11",
        "D03",
        "D11",
        "E03",
        "E11",
        "F03",
        "F11",
        "G11",
    ],
}

df_annot_ready = df_annot_clean.copy()
df_annot_ready["__well_norm__"] = df_annot_ready["Metadata_Well"].map(norm_well)

rem_mask = pd.Series(False, index=df_annot_ready.index)
for plate, wells in EXCLUDE_WELLS.items():
    wells = [norm_well(w) for w in wells]
    rem_mask |= (df_annot_ready["Metadata_Plate"] == plate) & (
        df_annot_ready["__well_norm__"].isin(wells)
    )

n_removed = int(rem_mask.sum())
if n_removed:
    print(f"ℹ️ Removendo {n_removed} linhas de poços técnicos antes da agregação.")
    df_annot_ready = df_annot_ready.loc[~rem_mask].drop(columns="__well_norm__")
else:
    df_annot_ready = df_annot_ready.drop(columns="__well_norm__", errors="ignore")

print("df_annot_ready:", df_annot_ready.shape)

df_annot_ready: (106609, 1820)

In [29]:
df_annot_ready.to_parquet(SINGLE_CELL_READY_PARQUET, index=False)
print("Checkpoint salvo:", SINGLE_CELL_READY_PARQUET)

Checkpoint salvo: /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/single_cell_ready.parquet

## Passo 6 — Agregar por poço (mediana)

A agregação agora usa `df_annot_ready` como entrada.  
Isso substitui o fluxo anterior em que a limpeza vinha **depois** da agregação.

In [30]:
AGG_STRATA = [
    "Metadata_Plate",
    "Metadata_Well",
    "Metadata_Control_Type",
    "Metadata_Treatment",
    "Metadata_Concentration",
    "Metadata_Cell_Type",
]

source_for_agg = (
    df_annot_ready
    if "df_annot_ready" in locals()
    else df_annot_clean if "df_annot_clean" in locals() else df_annot
)

AGG_STRATA = [c for c in AGG_STRATA if c in source_for_agg.columns]

cp_features = infer_cp_features(source_for_agg)

df_agg = (
    source_for_agg.groupby(AGG_STRATA, dropna=False)[cp_features].median().reset_index()
)

print("AGG_STRATA:", AGG_STRATA)
print("df_agg:", df_agg.shape)
display(df_agg.head(3))

AGG_STRATA: ['Metadata_Plate', 'Metadata_Well', 'Metadata_Control_Type', 'Metadata_Treatment', 'Metadata_Concentration', 'Metadata_Cell_Type']
df_agg: (180, 1813)

,Metadata_Plate,Metadata_Well,Metadata_Control_Type,Metadata_Treatment,Metadata_Concentration,Metadata_Cell_Type,Cells_Number_Object_Number,Cells_AreaShape_Area,Cells_AreaShape_BoundingBoxArea,Cells_AreaShape_BoundingBoxMaximum_X,Cells_AreaShape_BoundingBoxMaximum_Y,Cells_AreaShape_BoundingBoxMinimum_X,Cells_AreaShape_BoundingBoxMinimum_Y,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_CentralMoment_0_0,Cells_AreaShape_CentralMoment_0_1,Cells_AreaShape_CentralMoment_0_2,Cells_AreaShape_CentralMoment_0_3,Cells_AreaShape_CentralMoment_1_0,Cells_AreaShape_CentralMoment_1_1,Cells_AreaShape_CentralMoment_1_2,Cells_AreaShape_CentralMoment_1_3,Cells_AreaShape_CentralMoment_2_0,Cells_AreaShape_CentralMoment_2_1,Cells_AreaShape_CentralMoment_2_2,Cells_AreaShape_CentralMoment_2_3,Cells_AreaShape_Compactness,Cells_AreaShape_ConvexArea,Cells_AreaShape_Eccentricity,Cells_AreaShape_EquivalentDiameter,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,Cells_AreaShape_HuMoment_0,Cells_AreaShape_HuMoment_1,Cells_AreaShape_HuMoment_2,Cells_AreaShape_HuMoment_3,Cells_AreaShape_HuMoment_4,Cells_AreaShape_HuMoment_5,Cells_AreaShape_HuMoment_6,Cells_AreaShape_InertiaTensorEigenvalues_0,Cells_AreaShape_InertiaTensorEigenvalues_1,Cells_AreaShape_InertiaTensor_0_0,Cells_AreaShape_InertiaTensor_0_1,Cells_AreaShape_InertiaTensor_1_0,Cells_AreaShape_InertiaTensor_1_1,Cells_AreaShape_MajorAxisLength,Cells_AreaShape_MaxFeretDiameter,Cells_AreaShape_MaximumRadius,Cells_AreaShape_MeanRadius,Cells_AreaShape_MedianRadius,Cells_AreaShape_MinFeretDiameter,Cells_AreaShape_MinorAxisLength,Cells_AreaShape_NormalizedMoment_0_0,Cells_AreaShape_NormalizedMoment_0_1,Cells_AreaShape_NormalizedMoment_0_2,Cells_AreaShape_NormalizedMoment_0_3,Cells_AreaShape_NormalizedMoment_1_0,Cells_AreaShape_NormalizedMoment_1_1,Cells_AreaShape_NormalizedMoment_1_2,Cells_AreaShape_NormalizedMoment_1_3,Cells_AreaShape_NormalizedMoment_2_0,Cells_AreaShape_NormalizedMoment_2_1,Cells_AreaShape_NormalizedMoment_2_2,Cells_AreaShape_NormalizedMoment_2_3,Cells_AreaShape_NormalizedMoment_3_0,Cells_AreaShape_NormalizedMoment_3_1,Cells_AreaShape_NormalizedMoment_3_2,Cells_AreaShape_NormalizedMoment_3_3,Cells_AreaShape_Orientation,Cells_AreaShape_Perimeter,Cells_AreaShape_Solidity,Cells_AreaShape_SpatialMoment_0_0,Cells_AreaShape_SpatialMoment_0_1,Cells_AreaShape_SpatialMoment_0_2,Cells_AreaShape_SpatialMoment_0_3,Cells_AreaShape_SpatialMoment_1_0,Cells_AreaShape_SpatialMoment_1_1,Cells_AreaShape_SpatialMoment_1_2,Cells_AreaShape_SpatialMoment_1_3,Cells_AreaShape_SpatialMoment_2_0,Cells_AreaShape_SpatialMoment_2_1,Cells_AreaShape_SpatialMoment_2_2,Cells_AreaShape_SpatialMoment_2_3,Cells_AreaShape_Zernike_0_0,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_2_2,Cells_AreaShape_Zernike_3_1,Cells_AreaShape_Zernike_3_3,Cells_AreaShape_Zernike_4_0,Cells_AreaShape_Zernike_4_2,Cells_AreaShape_Zernike_4_4,Cells_AreaShape_Zernike_5_1,Cells_AreaShape_Zernike_5_3,Cells_AreaShape_Zernike_5_5,Cells_AreaShape_Zernike_6_0,Cells_AreaShape_Zernike_6_2,Cells_AreaShape_Zernike_6_4,...,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_00_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_01_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_02_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_03_256,Nuclei_Texture_SumAverage_AOGFP_10_00_256,Nuclei_Texture_SumAverage_AOGFP_10_01_256,Nuclei_Texture_SumAverage_AOGFP_10_02_256,Nuclei_Texture_SumAverage_AOGFP_10_03_256,Nuclei_Texture_SumAverage_AOGFP_20_00_256,Nuclei_Texture_SumAverage_AOGFP_20_01_256,Nuclei_Texture_SumAverage_AOGFP_20_02_256,Nuclei_Texture_SumAverage_AOGFP_20_03_256,Nuclei_Texture_SumAverage_AOGFP_5_00_256,Nuclei_Texture_SumAverage_AOGFP_5_01_256,Nuclei_Texture_SumAverage_AOGFP_5_02_256,Nuclei_Texture_SumAverage_AOGFP_5_03_256,Nuclei_Texture_SumAverage_AOPI_10_00_256,Nuclei_Texture_SumAverage_AOPI_10_01_256,Nuclei_Texture_SumAverage_AOPI_10_02_256,Nuclei_Texture_SumAverage_AOPI_10_03_256,Nuclei_Texture_SumAverage_AOPI_20_00_256,Nuclei_Texture_SumAverage_AOPI_20_01_256,Nuclei_Texture_SumAverage_AOPI_20_02_256,Nuclei_Texture_SumAverage_AOPI_20_03_256,Nuclei_Texture_SumAverage_AOPI_5_00_256,Nuclei_Texture_SumAverage_AOPI_5_01_256,Nuclei_Texture_SumAverage_AOPI_5_02_256,Nuclei_Texture_SumAverage_AOPI_5_03_256,Nuclei_Texture_SumEntropy_AOGFP_10_00_256,Nuclei_Texture_SumEntropy_AOGFP_10_01_256,Nuclei_Texture_SumEntropy_AOGFP_10_02_256,Nuclei_Texture_SumEntropy_AOGFP_10_03_256,Nuclei_Texture_SumEntropy_AOGFP_20_00_256,Nuclei_Texture_SumEntropy_AOGFP_20_01_256,Nuclei_Texture_SumEntropy_AOGFP_20_02_256,Nuclei_Texture_SumEntropy_AOGFP_20_03_256,Nuclei_Texture_SumEntropy_AOGFP_5_00_256,Nuclei_Texture_SumEntropy_AOGFP_5_01_256,Nuclei_Texture_SumEntropy_AOGFP_5_02_256,Nuclei_Texture_SumEntropy_AOGFP_5_03_256,Nuclei_Texture_SumEntropy_AOPI_10_00_256,Nuclei_Texture_SumEntropy_AOPI_10_01_256,Nuclei_Texture_SumEntropy_AOPI_10_02_256,Nuclei_Texture_SumEntropy_AOPI_10_03_256,Nuclei_Texture_SumEntropy_AOPI_20_00_256,Nuclei_Texture_SumEntropy_AOPI_20_01_256,Nuclei_Texture_SumEntropy_AOPI_20_02_256,Nuclei_Texture_SumEntropy_AOPI_20_03_256,Nuclei_Texture_SumEntropy_AOPI_5_00_256,Nuclei_Texture_SumEntropy_AOPI_5_01_256,Nuclei_Texture_SumEntropy_AOPI_5_02_256,Nuclei_Texture_SumEntropy_AOPI_5_03_256,Nuclei_Texture_SumVariance_AOGFP_10_00_256,Nuclei_Texture_SumVariance_AOGFP_10_01_256,Nuclei_Texture_SumVariance_AOGFP_10_02_256,Nuclei_Texture_SumVariance_AOGFP_10_03_256,Nuclei_Texture_SumVariance_AOGFP_20_00_256,Nuclei_Texture_SumVariance_AOGFP_20_01_256,Nuclei_Texture_SumVariance_AOGFP_20_02_256,Nuclei_Texture_SumVariance_AOGFP_20_03_256,Nuclei_Texture_SumVariance_AOGFP_5_00_256,Nuclei_Texture_SumVariance_AOGFP_5_01_256,Nuclei_Texture_SumVariance_AOGFP_5_02_256,Nuclei_Texture_SumVariance_AOGFP_5_03_256,Nuclei_Texture_SumVariance_AOPI_10_00_256,Nuclei_Texture_SumVariance_AOPI_10_01_256,Nuclei_Texture_SumVariance_AOPI_10_02_256,Nuclei_Texture_SumVariance_AOPI_10_03_256,Nuclei_Texture_SumVariance_AOPI_20_00_256,Nuclei_Texture_SumVariance_AOPI_20_01_256,Nuclei_Texture_SumVariance_AOPI_20_02_256,Nuclei_Texture_SumVariance_AOPI_20_03_256,Nuclei_Texture_SumVariance_AOPI_5_00_256,Nuclei_Texture_SumVariance_AOPI_5_01_256,Nuclei_Texture_SumVariance_AOPI_5_02_256,Nuclei_Texture_SumVariance_AOPI_5_03_256,Nuclei_Texture_Variance_AOGFP_10_00_256,Nuclei_Texture_Variance_AOGFP_10_01_256,Nuclei_Texture_Variance_AOGFP_10_02_256,Nuclei_Texture_Variance_AOGFP_10_03_256,Nuclei_Texture_Variance_AOGFP_20_00_256,Nuclei_Texture_Variance_AOGFP_20_01_256,Nuclei_Texture_Variance_AOGFP_20_02_256,Nuclei_Texture_Variance_AOGFP_20_03_256,Nuclei_Texture_Variance_AOGFP_5_00_256,Nuclei_Texture_Variance_AOGFP_5_01_256,Nuclei_Texture_Variance_AOGFP_5_02_256,Nuclei_Texture_Variance_AOGFP_5_03_256,Nuclei_Texture_Variance_AOPI_10_00_256,Nuclei_Texture_Variance_AOPI_10_01_256,Nuclei_Texture_Variance_AOPI_10_02_256,Nuclei_Texture_Variance_AOPI_10_03_256,Nuclei_Texture_Variance_AOPI_20_00_256,Nuclei_Texture_Variance_AOPI_20_01_256,Nuclei_Texture_Variance_AOPI_20_02_256,Nuclei_Texture_Variance_AOPI_20_03_256,Nuclei_Texture_Variance_AOPI_5_00_256,Nuclei_Texture_Variance_AOPI_5_01_256,Nuclei_Texture_Variance_AOPI_5_02_256,Nuclei_Texture_Variance_AOPI_5_03_256
0,260221_171841_Plate_1_R1,B02,negcon,Non-treated,0.00000,HUH-7,31.0,9970.0,17388.0,675.0,501.0,533.0,372.0,608.629524,438.145028,9970.0,0.0,9.536622e+06,-1.756979e+05,-1.544009e-11,66179.224855,-3.301106e+05,4.756275e+06,8.905594e+06,6.820414e+05,7.374573e+09,2.292795e+08,1.965376,11486.0,0.748653,112.668533,1.0,0.587127,0.508808,0.189883,0.005494,0.000751,0.000038,5.556760e-10,2.663775e-07,-1.643082e-13,1333.503348,582.512514,916.454165,-10.886409,-10.886409,909.933597,146.068660,157.876534,41.048752,14.380256,12.727922,101.589330,96.541184,NaN,NaN,0.091809,-0.000053,NaN,0.000979,-0.000117,0.000091,0.091032,0.000181,0.007116,0.000043,0.000327,0.000387,-0.000015,0.000051,3.302874,520.156421,0.876495,9970.0,659123.0,53629518.0,4.839516e+09,633185.0,40253113.0,3.344315e+09,3.123659e+11,48472415.0,3.135399e+09,2.410649e+11,2.281490e+13,0.498011,0.059320,0.175601,0.052095,0.029453,0.017744,0.017500,0.029038,0.020416,0.014187,0.014317,0.009003,0.010880,0.010855,0.013309,...,0.169987,0.144748,0.169251,0.143198,161.658661,161.381406,161.347518,161.706667,148.084016,139.583541,148.955504,139.293366,161.202080,161.426362,160.855947,161.251418,73.147606,72.472231,72.914153,72.089247,66.935860,63.879397,67.011707,63.966006,72.196405,72.644864,71.936382,72.448099,6.496402,6.405683,6.496940,6.409983,6.190401,5.662998,6.199212,5.703244,6.644093,6.580507,6.637542,6.579803,5.837658,5.750454,5.825824,5.761128,5.576764,5.207737,5.562471,5.208818,5.905050,5.884681,5.913418,5.879702,791.506907,732.811405,834.654062,740.215085,563.370143,310.041670,517.710795,288.520710,1070.572738,943.511628,1051.218015,899.000701,337.650774,322.133558,360.218665,318.086756,250.899756,164.206165,253.598816,153.699446,455.038452,407.540742,458.582494,398.166789,396.247419,414.963872,406.618015,412.841640,327.736310,218.080357,310.800029,210.481967,375.441136,383.229788,372.828323,391.611768,167.790566,170.491505,170.155411,171.035807,140.815290,101.541963,135.624549,97.253713,161.741689,163.698694,164.942275,163.873030
1,260221_171841_Plate_1_R1,B03,trt,NPPS420,0.00025,HUH-7,32.0,11984.0,21000.0,702.0,465.0,552.0,319.0,631.663010,390.778764,11984.0,0.0,1.274838e+07,2.593746e+06,8.981260e-12,169967.706456,-1.394835e+06,1.440089e+08,1.290554e+07,-2.237329e+06,1.240055e+10,2.442492e+07,2.027724,13838.0,0.744709,123.525312,1.0,0.585791,0.493164,0.189119,0.005266,0.000730,0.000033,4.942812e-10,2.354618e-07,6.552841e-14,1593.342923,676.285120,1093.695609,-21.700731,-21.700731,1079.880455,159.666799,171.592541,45.000000,15.526289,13.601471,109.913120,104.021930,NaN,NaN,0.092374,0.000494,NaN,0.001886,-0.000140,0.000325,0.091351,-0.000299,0.006798,0.000003,0.000202,0.000195,0.000033,0.000048,2.839041,559.428499,0.872980,11984.0,832383.0,70802652.0,6.696564e+09,820827.0,57386215.0,4.967991e+09,4.934329e+11,70894654.0,4.945806e+09,4.163616e+11,4.092359e+13,0.498792,0.059869,0.175330,0.051599,0.030378,0.018455,0.016702,0.028948,0.019914,0.015068,0.014243,0.008904,0.009978,0.010868,0.013547,...,0.200106,0.173238,0.197740,0.173694,126.199017,126.512522,126.156098,126.343100,121.683099,116.889640,121.707424,119.143946,125.950112,126.061009,125.739896,125.691914,60.568880,60.398967,60.800860,60.814965,58.598753,56.946844,58.564155,58.412104,60.906658,60.746600,60.800464,60.907015,5.922995,5.890795,5.932721,5.893202,5.735147,5.389732,5.741011,5.476184,6.015435,5.957697,6.019622,5.971626,5.641809,5.575574,5.635175,5.574713,5.502489,5.227724,5.492878,5.281613,5.708957,5.675938,5.716124,5.670605,374.838613,353.368942,374.061221,349.907287,272.744185,184.686893,270.680310,193.675421,467.673926,434.900791,480.447208,408.316898,316.347170,285.951225,318.693860,288.148860,252.872862,176.558110,236.621896,181.244854,413.397521,350.329243,419.043716,349.773123,168.973699,177.280020,171.388904,180.783459,148.048334,115.604065,145.720745,116.329004,161.109616,164.493912,160.896130,164.888288,145.343058,147.055819,142.766288,147.002339,128.213909,99.306191,127.118742,107.725329,145.504021,140.686453,146.778091,146.921312
2,260221_171841_Plate_1_R1,B04,negcon,Lactose,10.00000,HUH-7,26.0,14058.0,23595.0,671.0,549.0,522.0,403.0,593.312404,478.529273,14058.0,0.0,1.839057e+07,-1.253340e+06,6.366463e-12,692.100234,1.012627e+06,5.291783e+07,1.781113e+07,1.407002e+05,2.082719e+10,-4.395768e+09,2.059032,15828.0,0.763036,133.787898,1.0,0.580390,0.485665,0.193877,0.006320,0.000993,0.000046,1.449729e-09,4.792465e-07,5.974627e-12,1886.208606,775.388472,1314.560707,-0.035143,-0.035143,1252.660221,173.722013,190.633156,47.885280,16.679237,14.370013,116.777015,111.383192,NaN,NaN,0.097080,-0.000207,NaN,0.000002,0.000108,0.000074,0.090457,0.000015,0.007159,-0.000049,-0.000359,0.000192,0.000026,0.000006,0.099287,607.464033,0.875836,14058.0,1067119.0,102265292.0,1.074921e+10,1052134.0,77600180.0,7.387236e+09,7.654370e+11,97337012.0,7.226391e+09,6.524414e+11,7.179108e+13,0.482237,0.061755,0.172272,0.051723,0.034021,0.017444,0.017023,0.030711,0.019494,0.014889,0.014765,0.009449,0.009394,0.010667,0.013493,...,0.190872,0.165331,0.193197,0.164353,149.835901,148.851149,149.517506,149.740385,146.025819,140.029326,145.479947,139.600704,148.639576,148.916949,148.799713,148.752788,67.448881,67.166302,67.398668,67.482931,64.605065,63.385615,64.259563,63.182917,67.266116,67.288157,67.291968,67.428034,6.004623,6.000890,6.035546,5.965688,5.839152,5.599020,5.843331,5.550634,6.086946,6.047323,6.093147,6.050480,5.573829,5.530531,5.590478,5.550352,5.480686,5.295456,5.488993,5.291536,5.688257,5.633811,5.697420,5.645345,380.381750,387.033326,401.466782,377.401950,317.510895,238.433397,321.186479,223.988626,508.015140,454.242075,515.683771,440.083480,257.505517,233.245253,257.090025,231.371094,204.342044,173.010864,219.268718,167.713028,344.738972,288.538165,335.324614,287.269201,186.046796,192.240142,186.146324,191.094283,175.314870,146.680900,176.600362,130.733418,174.485210,178.244131,173.152563,179.901020,114.755237,121.366594,119.254012,116.040175,110.156386,94.698347,107.428177,90.818062,116.927778,117.449666,116.136004,118.891457

> **Nota de simplificação**  
> A reanotação de `df_agg` via platemap foi removida.  
> Como a anotação já acontece em `df_annot` e a limpeza é feita antes da agregação, `df_agg` herda os metadados necessários de forma mais consistente.

In [31]:
df_agg.to_parquet(PER_WELL_AGGREGATED_PARQUET, index=False)
print("Checkpoint salvo:", PER_WELL_AGGREGATED_PARQUET)

Checkpoint salvo: /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/per_well_aggregated.parquet

## Passo 7 — Normalizar (plate-wise `mad_robustize`)

In [32]:
# --- Config ----
NORMALIZE_MODE = "negcon"  # ou "all" se quiser normalizar usando todas as amostras
MAD_EPS = 1e-9

from pycytominer.normalize import normalize as pc_normalize
from pycytominer.cyto_utils import infer_cp_features

# --- Enforce negcon-only normalization (sem fallback) ---
if NORMALIZE_MODE == "negcon":
    control_cols = [
        c for c in ("Metadata_Control_Type", "Control_Type") if c in df_agg.columns
    ]
    if not control_cols:
        raise ValueError(
            "NORMALIZE_MODE='negcon' requisitado, mas nenhuma coluna de controle "
            "foi encontrada (esperado: 'Metadata_Control_Type' ou 'Control_Type')."
        )
    col = control_cols[0]
    # normaliza string para comparação robusta
    df_agg[col] = df_agg[col].astype(str).str.strip().str.lower()
    samples_q = f'{col} == "negcon"'

    # garante que existem amostras negcon
    if df_agg.query(samples_q).shape[0] == 0:
        raise ValueError(
            "NORMALIZE_MODE='negcon' requisitado, mas não há linhas com controle negativo "
            f"(condição: {samples_q}). Verifique o plate map/anotação."
        )
else:
    samples_q = None

# --- Seleção de features e metadados ---
cp_features = infer_cp_features(df_agg)
meta_cols = [c for c in df_agg.columns if c.startswith("Metadata_")] + [
    c
    for c in (
        "Control_Type",
        "Treatment",
        "Concentration",
        "Cell_Type",
        "plate_map_name",
    )
    if c in df_agg.columns
]

# --- Normalização ---
kwargs = dict(
    profiles=df_agg,
    features=cp_features,
    method="mad_robustize",
    mad_robustize_epsilon=MAD_EPS,
    meta_features=meta_cols,
)
if samples_q is not None:
    kwargs["samples"] = samples_q

df_norm = pc_normalize(**kwargs)

print("df_norm:", df_norm.shape)
display(df_norm.head(3))

df_norm: (180, 1813)

,Metadata_Plate,Metadata_Well,Metadata_Control_Type,Metadata_Treatment,Metadata_Concentration,Metadata_Cell_Type,Cells_Number_Object_Number,Cells_AreaShape_Area,Cells_AreaShape_BoundingBoxArea,Cells_AreaShape_BoundingBoxMaximum_X,Cells_AreaShape_BoundingBoxMaximum_Y,Cells_AreaShape_BoundingBoxMinimum_X,Cells_AreaShape_BoundingBoxMinimum_Y,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_CentralMoment_0_0,Cells_AreaShape_CentralMoment_0_1,Cells_AreaShape_CentralMoment_0_2,Cells_AreaShape_CentralMoment_0_3,Cells_AreaShape_CentralMoment_1_0,Cells_AreaShape_CentralMoment_1_1,Cells_AreaShape_CentralMoment_1_2,Cells_AreaShape_CentralMoment_1_3,Cells_AreaShape_CentralMoment_2_0,Cells_AreaShape_CentralMoment_2_1,Cells_AreaShape_CentralMoment_2_2,Cells_AreaShape_CentralMoment_2_3,Cells_AreaShape_Compactness,Cells_AreaShape_ConvexArea,Cells_AreaShape_Eccentricity,Cells_AreaShape_EquivalentDiameter,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,Cells_AreaShape_HuMoment_0,Cells_AreaShape_HuMoment_1,Cells_AreaShape_HuMoment_2,Cells_AreaShape_HuMoment_3,Cells_AreaShape_HuMoment_4,Cells_AreaShape_HuMoment_5,Cells_AreaShape_HuMoment_6,Cells_AreaShape_InertiaTensorEigenvalues_0,Cells_AreaShape_InertiaTensorEigenvalues_1,Cells_AreaShape_InertiaTensor_0_0,Cells_AreaShape_InertiaTensor_0_1,Cells_AreaShape_InertiaTensor_1_0,Cells_AreaShape_InertiaTensor_1_1,Cells_AreaShape_MajorAxisLength,Cells_AreaShape_MaxFeretDiameter,Cells_AreaShape_MaximumRadius,Cells_AreaShape_MeanRadius,Cells_AreaShape_MedianRadius,Cells_AreaShape_MinFeretDiameter,Cells_AreaShape_MinorAxisLength,Cells_AreaShape_NormalizedMoment_0_0,Cells_AreaShape_NormalizedMoment_0_1,Cells_AreaShape_NormalizedMoment_0_2,Cells_AreaShape_NormalizedMoment_0_3,Cells_AreaShape_NormalizedMoment_1_0,Cells_AreaShape_NormalizedMoment_1_1,Cells_AreaShape_NormalizedMoment_1_2,Cells_AreaShape_NormalizedMoment_1_3,Cells_AreaShape_NormalizedMoment_2_0,Cells_AreaShape_NormalizedMoment_2_1,Cells_AreaShape_NormalizedMoment_2_2,Cells_AreaShape_NormalizedMoment_2_3,Cells_AreaShape_NormalizedMoment_3_0,Cells_AreaShape_NormalizedMoment_3_1,Cells_AreaShape_NormalizedMoment_3_2,Cells_AreaShape_NormalizedMoment_3_3,Cells_AreaShape_Orientation,Cells_AreaShape_Perimeter,Cells_AreaShape_Solidity,Cells_AreaShape_SpatialMoment_0_0,Cells_AreaShape_SpatialMoment_0_1,Cells_AreaShape_SpatialMoment_0_2,Cells_AreaShape_SpatialMoment_0_3,Cells_AreaShape_SpatialMoment_1_0,Cells_AreaShape_SpatialMoment_1_1,Cells_AreaShape_SpatialMoment_1_2,Cells_AreaShape_SpatialMoment_1_3,Cells_AreaShape_SpatialMoment_2_0,Cells_AreaShape_SpatialMoment_2_1,Cells_AreaShape_SpatialMoment_2_2,Cells_AreaShape_SpatialMoment_2_3,Cells_AreaShape_Zernike_0_0,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_2_2,Cells_AreaShape_Zernike_3_1,Cells_AreaShape_Zernike_3_3,Cells_AreaShape_Zernike_4_0,Cells_AreaShape_Zernike_4_2,Cells_AreaShape_Zernike_4_4,Cells_AreaShape_Zernike_5_1,Cells_AreaShape_Zernike_5_3,Cells_AreaShape_Zernike_5_5,Cells_AreaShape_Zernike_6_0,Cells_AreaShape_Zernike_6_2,Cells_AreaShape_Zernike_6_4,...,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_00_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_01_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_02_256,Nuclei_Texture_InverseDifferenceMoment_AOPI_5_03_256,Nuclei_Texture_SumAverage_AOGFP_10_00_256,Nuclei_Texture_SumAverage_AOGFP_10_01_256,Nuclei_Texture_SumAverage_AOGFP_10_02_256,Nuclei_Texture_SumAverage_AOGFP_10_03_256,Nuclei_Texture_SumAverage_AOGFP_20_00_256,Nuclei_Texture_SumAverage_AOGFP_20_01_256,Nuclei_Texture_SumAverage_AOGFP_20_02_256,Nuclei_Texture_SumAverage_AOGFP_20_03_256,Nuclei_Texture_SumAverage_AOGFP_5_00_256,Nuclei_Texture_SumAverage_AOGFP_5_01_256,Nuclei_Texture_SumAverage_AOGFP_5_02_256,Nuclei_Texture_SumAverage_AOGFP_5_03_256,Nuclei_Texture_SumAverage_AOPI_10_00_256,Nuclei_Texture_SumAverage_AOPI_10_01_256,Nuclei_Texture_SumAverage_AOPI_10_02_256,Nuclei_Texture_SumAverage_AOPI_10_03_256,Nuclei_Texture_SumAverage_AOPI_20_00_256,Nuclei_Texture_SumAverage_AOPI_20_01_256,Nuclei_Texture_SumAverage_AOPI_20_02_256,Nuclei_Texture_SumAverage_AOPI_20_03_256,Nuclei_Texture_SumAverage_AOPI_5_00_256,Nuclei_Texture_SumAverage_AOPI_5_01_256,Nuclei_Texture_SumAverage_AOPI_5_02_256,Nuclei_Texture_SumAverage_AOPI_5_03_256,Nuclei_Texture_SumEntropy_AOGFP_10_00_256,Nuclei_Texture_SumEntropy_AOGFP_10_01_256,Nuclei_Texture_SumEntropy_AOGFP_10_02_256,Nuclei_Texture_SumEntropy_AOGFP_10_03_256,Nuclei_Texture_SumEntropy_AOGFP_20_00_256,Nuclei_Texture_SumEntropy_AOGFP_20_01_256,Nuclei_Texture_SumEntropy_AOGFP_20_02_256,Nuclei_Texture_SumEntropy_AOGFP_20_03_256,Nuclei_Texture_SumEntropy_AOGFP_5_00_256,Nuclei_Texture_SumEntropy_AOGFP_5_01_256,Nuclei_Texture_SumEntropy_AOGFP_5_02_256,Nuclei_Texture_SumEntropy_AOGFP_5_03_256,Nuclei_Texture_SumEntropy_AOPI_10_00_256,Nuclei_Texture_SumEntropy_AOPI_10_01_256,Nuclei_Texture_SumEntropy_AOPI_10_02_256,Nuclei_Texture_SumEntropy_AOPI_10_03_256,Nuclei_Texture_SumEntropy_AOPI_20_00_256,Nuclei_Texture_SumEntropy_AOPI_20_01_256,Nuclei_Texture_SumEntropy_AOPI_20_02_256,Nuclei_Texture_SumEntropy_AOPI_20_03_256,Nuclei_Texture_SumEntropy_AOPI_5_00_256,Nuclei_Texture_SumEntropy_AOPI_5_01_256,Nuclei_Texture_SumEntropy_AOPI_5_02_256,Nuclei_Texture_SumEntropy_AOPI_5_03_256,Nuclei_Texture_SumVariance_AOGFP_10_00_256,Nuclei_Texture_SumVariance_AOGFP_10_01_256,Nuclei_Texture_SumVariance_AOGFP_10_02_256,Nuclei_Texture_SumVariance_AOGFP_10_03_256,Nuclei_Texture_SumVariance_AOGFP_20_00_256,Nuclei_Texture_SumVariance_AOGFP_20_01_256,Nuclei_Texture_SumVariance_AOGFP_20_02_256,Nuclei_Texture_SumVariance_AOGFP_20_03_256,Nuclei_Texture_SumVariance_AOGFP_5_00_256,Nuclei_Texture_SumVariance_AOGFP_5_01_256,Nuclei_Texture_SumVariance_AOGFP_5_02_256,Nuclei_Texture_SumVariance_AOGFP_5_03_256,Nuclei_Texture_SumVariance_AOPI_10_00_256,Nuclei_Texture_SumVariance_AOPI_10_01_256,Nuclei_Texture_SumVariance_AOPI_10_02_256,Nuclei_Texture_SumVariance_AOPI_10_03_256,Nuclei_Texture_SumVariance_AOPI_20_00_256,Nuclei_Texture_SumVariance_AOPI_20_01_256,Nuclei_Texture_SumVariance_AOPI_20_02_256,Nuclei_Texture_SumVariance_AOPI_20_03_256,Nuclei_Texture_SumVariance_AOPI_5_00_256,Nuclei_Texture_SumVariance_AOPI_5_01_256,Nuclei_Texture_SumVariance_AOPI_5_02_256,Nuclei_Texture_SumVariance_AOPI_5_03_256,Nuclei_Texture_Variance_AOGFP_10_00_256,Nuclei_Texture_Variance_AOGFP_10_01_256,Nuclei_Texture_Variance_AOGFP_10_02_256,Nuclei_Texture_Variance_AOGFP_10_03_256,Nuclei_Texture_Variance_AOGFP_20_00_256,Nuclei_Texture_Variance_AOGFP_20_01_256,Nuclei_Texture_Variance_AOGFP_20_02_256,Nuclei_Texture_Variance_AOGFP_20_03_256,Nuclei_Texture_Variance_AOGFP_5_00_256,Nuclei_Texture_Variance_AOGFP_5_01_256,Nuclei_Texture_Variance_AOGFP_5_02_256,Nuclei_Texture_Variance_AOGFP_5_03_256,Nuclei_Texture_Variance_AOPI_10_00_256,Nuclei_Texture_Variance_AOPI_10_01_256,Nuclei_Texture_Variance_AOPI_10_02_256,Nuclei_Texture_Variance_AOPI_10_03_256,Nuclei_Texture_Variance_AOPI_20_00_256,Nuclei_Texture_Variance_AOPI_20_01_256,Nuclei_Texture_Variance_AOPI_20_02_256,Nuclei_Texture_Variance_AOPI_20_03_256,Nuclei_Texture_Variance_AOPI_5_00_256,Nuclei_Texture_Variance_AOPI_5_01_256,Nuclei_Texture_Variance_AOPI_5_02_256,Nuclei_Texture_Variance_AOPI_5_03_256
0,260221_171841_Plate_1_R1,B02,negcon,Non-treated,0.00000,HUH-7,1.686227,-2.937607,-3.476119,-0.277731,-0.938422,0.366152,0.435609,0.229116,-0.087450,-2.937607,0.0,-2.383812,-0.235600,-0.015277,-0.213188,-0.261603,-0.638756,-2.740402,0.468864,-2.256724,0.252439,-0.914061,-3.016653,-0.436290,-3.111346,0.0,0.353525,0.971592,-0.366021,-0.339013,-1.010468,-0.001932,-0.047269,0.163491,-0.000168,-3.440029,-2.385359,-2.787757,0.138616,0.138616,-2.855869,-3.698444,-3.320374,-2.793195,-2.264856,-1.625199,-2.822176,-2.498784,NaN,NaN,-0.988504,-0.334548,NaN,-0.139945,-0.459257,-0.295441,-0.116844,0.819155,0.509515,1.285000,1.671730,0.656204,-0.201939,0.285318,0.139367,-2.607470,0.151978,-2.937607,-2.740012,-2.528026,-2.399813,-2.988510,-2.597471,-2.342969,-2.186666,-2.688119,-2.431025,-2.414269,-2.046772,0.370081,-0.097038,-0.184388,-0.376600,-0.447186,-1.088955,0.351280,-1.350220,1.382027,-0.954641,-1.570045,0.020592,2.180831,-0.699939,-0.622769,...,-2.016802,-2.010622,-2.061806,-2.025023,0.064137,0.059742,0.055992,0.062873,-0.070231,-0.178524,-0.056439,-0.177272,0.078788,0.066952,0.066082,0.062904,1.888526,1.806401,1.877426,1.808959,1.486373,1.306952,1.499540,1.319638,1.834465,1.842458,1.799088,1.841187,1.244208,1.207594,1.227024,1.189718,0.991124,0.590803,1.031778,0.671336,1.382657,1.270117,1.327027,1.284062,2.528560,2.375761,2.355197,2.211297,1.907136,1.580777,1.918385,1.530536,2.364744,2.463579,2.364131,2.453644,2.372346,2.238934,2.572050,2.205441,1.889989,1.182441,1.677587,0.879787,2.477094,2.501350,2.456080,2.414747,5.381582,5.379610,6.007564,5.407665,4.455441,2.723296,4.527822,2.471635,5.300002,5.611121,5.316528,5.634584,2.540707,2.659299,2.677938,2.603524,2.362511,1.525901,2.101070,1.389834,2.593525,2.605608,2.571009,2.752100,5.737177,5.653423,5.869764,5.638728,5.021003,3.340737,4.813740,3.258373,5.596476,5.668243,5.415181,5.606710
1,260221_171841_Plate_1_R1,B03,trt,NPPS420,0.00025,HUH-7,2.023472,-1.224588,-1.333410,0.793519,-3.049871,1.098456,-2.543392,1.150778,-2.963177,-1.224588,0.0,-1.302674,2.461245,0.008886,0.521257,-1.301110,0.367069,-1.268666,-2.059295,-1.186781,0.059060,-0.231399,-1.321778,-0.852581,-1.241628,0.0,0.115131,0.238398,-0.759710,-0.805854,-1.314368,-0.811406,-0.096288,-0.211824,0.000061,-1.551375,-1.095535,-1.244982,-0.470940,-0.470940,-1.194102,-1.599121,-1.661858,-1.073293,-0.959178,-0.685652,-1.281518,-1.107483,NaN,NaN,-0.682783,2.407200,NaN,0.412243,-0.572502,0.533441,0.061739,-1.757960,-1.645128,0.173627,0.950190,-0.052391,1.095054,0.237502,0.021928,-1.273183,-0.193528,-1.224588,-1.416356,-1.462749,-1.475364,-1.423688,-1.347391,-1.284818,-1.195756,-1.255494,-1.230611,-1.335368,-1.151094,0.459584,0.194763,-0.295826,-0.756772,0.272233,-0.050771,-0.659512,-1.468493,0.148759,0.714701,-1.723813,-0.245217,0.194124,-0.658287,0.020981,...,-1.453045,-1.469761,-1.520319,-1.442954,-0.555738,-0.551665,-0.560054,-0.557339,-0.540248,-0.608196,-0.545189,-0.554855,-0.537903,-0.552701,-0.556534,-0.555899,1.052562,1.014438,1.069893,1.056575,0.958011,0.877084,0.962880,0.970609,1.077619,1.052638,1.058157,1.072966,0.061088,0.080008,0.064891,0.098586,0.080523,-0.040314,0.103830,0.157536,0.059477,-0.004575,0.057518,0.047033,2.024472,1.929721,1.891766,1.769934,1.753350,1.626026,1.770627,1.685858,1.873679,1.939690,1.874402,1.928207,0.325929,0.288538,0.292935,0.258835,0.127769,0.053002,0.137563,0.077404,0.241648,0.338112,0.297066,0.272173,4.923800,4.579872,5.090156,4.722628,4.502734,3.032435,4.118805,3.157091,4.647139,4.568548,4.697079,4.725575,0.229877,0.276646,0.266007,0.302609,0.186271,0.091514,0.144871,0.092443,0.263070,0.265204,0.257389,0.281405,4.716034,4.615750,4.608096,4.580190,4.426865,3.235042,4.408222,3.770102,4.840924,4.599392,4.610337,4.831014
2,260221_171841_Plate_1_R1,B04,negcon,Lactose,10.00000,HUH-7,0.000000,0.539465,0.205996,-0.436435,1.876844,-0.057813,2.178043,-0.383784,2.364381,0.539465,0.0,0.596592,-1.284992,0.006299,-0.676598,1.049331,-0.290884,0.536286,0.000066,0.607100,-4.113529,0.111401,0.112235,1.082055,0.525760,0.0,-0.848107,-0.113030,1.692497,1.349054,2.514290,1.360543,0.666555,2.747705,0.005958,0.577331,0.267613,0.677510,0.750254,0.750254,0.495364,0.570767,0.640502,0.182614,0.354378,0.140957,-0.011073,0.261595,NaN,NaN,1.864405,-1.107547,NaN,-0.735482,0.689148,-0.355385,-0.439304,-0.071910,0.799661,-1.246932,-2.290725,-0.061675,0.927353,-0.694401,-0.671759,0.358846,0.087154,0.539465,0.376958,0.488928,0.542067,0.505274,0.127477,0.291806,0.292818,0.433990,0.281562,0.117637,0.375648,-1.438254,1.196960,-1.551537,-0.661485,3.102665,-1.527285,-0.252957,0.865425,-0.880813,0.375327,-0.634340,1.209177,-1.092706,-1.321545,-0.126196,...,-1.625883,-1.619866,-1.606665,-1.621236,-0.142538,-0.159969,-0.151099,-0.146994,-0.106873,-0.170084,-0.118780,-0.171512,-0.140978,-0.152231,-0.147678,-0.154596,1.509797,1.458351,1.509736,1.501559,1.338660,1.276334,1.324701,1.270426,1.503947,1.486874,1.490071,1.507031,0.229511,0.321112,0.276682,0.251633,0.288555,0.443042,0.311048,0.326005,0.209992,0.178861,0.208574,0.207422,1.849501,1.814837,1.783116,1.712256,1.708207,1.779357,1.762377,1.707030,1.821842,1.833963,1.827974,1.864730,0.353154,0.461578,0.428544,0.395961,0.399213,0.537255,0.452426,0.333851,0.391226,0.420375,0.430353,0.410882,3.659383,3.414911,3.729142,3.423442,3.339509,2.943656,3.700723,2.820357,3.570683,3.442521,3.385464,3.551524,0.403469,0.426613,0.417323,0.404843,0.516502,0.526505,0.510796,0.290930,0.408505,0.412327,0.391190,0.445005,3.324586,3.478296,3.525012,3.216484,3.575479,3.017207,3.469466,2.943874,3.511249,3.520112,3.252605,3.548392

In [33]:
df_norm.to_parquet(PER_WELL_NORMALIZED_PARQUET, index=False)
print("Checkpoint salvo:", PER_WELL_NORMALIZED_PARQUET)

Checkpoint salvo: /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/per_well_normalized.parquet

## Passo 8 — Feature selection

In [34]:
# --- Imports robustos para diferentes versões do pycytominer ---
try:
    from pycytominer.feature_select import feature_select as pc_feature_select
except Exception:
    # algumas versões expõem em pycytominer.feature_select (módulo) ou diretamente em pycytominer
    try:
        from pycytominer import feature_select as pc_feature_select
    except Exception as e:
        raise ImportError(
            "Não foi possível importar feature_select do pycytominer"
        ) from e

from pycytominer.cyto_utils import infer_cp_features

# --- Parâmetros padrão (defina se ainda não existirem no seu notebook) ---
FS_OPS = [
    "correlation_threshold",
    "variance_threshold",
    "drop_na_columns",
    "drop_outliers",
]
OUTLIER_CUTOFF = 15  # ajuste se quiser mais/menos agressivo
CORR_THRESHOLD = 0.90
NA_CUTOFF = 0.05

# --- Seleção de features (robusto a variações de API) ---
# 1) Detecta features automaticamente
cp_features = infer_cp_features(df_norm)
meta_cols = [c for c in df_norm.columns if c not in cp_features]
features_cols = cp_features


# 2) Chama o feature_select tentando diferentes assinaturas
def run_feature_select_returning_meta(df, features):
    # Tenta com 'return_meta' e argumento 'operation'
    try:
        return pc_feature_select(
            profiles=df,
            features=features,
            operation=FS_OPS,  # algumas versões usam 'operation'
            corr_threshold=CORR_THRESHOLD,
            na_cutoff=NA_CUTOFF,
            outlier_cutoff=OUTLIER_CUTOFF,
            return_meta=True,  # mantém metadados se suportado
        )
    except TypeError:
        # Tenta com 'operations' (plural)
        try:
            return pc_feature_select(
                profiles=df,
                features=features,
                operations=FS_OPS,
                corr_threshold=CORR_THRESHOLD,
                na_cutoff=NA_CUTOFF,
                outlier_cutoff=OUTLIER_CUTOFF,
                return_meta=True,
            )
        except TypeError:
            # Fallback final: sem return_meta -> roda só nas features e reconcatena meta
            try:
                df_fs_only = pc_feature_select(
                    profiles=df,
                    features=features,
                    operation=FS_OPS,
                    corr_threshold=CORR_THRESHOLD,
                    na_cutoff=NA_CUTOFF,
                    outlier_cutoff=OUTLIER_CUTOFF,
                )
            except TypeError:
                # última tentativa com 'operations'
                df_fs_only = pc_feature_select(
                    profiles=df,
                    features=features,
                    operations=FS_OPS,
                    corr_threshold=CORR_THRESHOLD,
                    na_cutoff=NA_CUTOFF,
                    outlier_cutoff=OUTLIER_CUTOFF,
                )
            # Garante que df_fs_only não traga de volta metadados já preservados
            df_fs_only = df_fs_only.drop(
                columns=[c for c in meta_cols if c in df_fs_only.columns],
                errors="ignore",
            ).copy()

            # Reanexa metadados preservando a ordem das linhas
            return pd.concat(
                [
                    df[meta_cols].reset_index(drop=True),
                    df_fs_only.reset_index(drop=True),
                ],
                axis=1,
            )

In [35]:
df_fs = run_feature_select_returning_meta(df_norm, features_cols)
print("df_fs:", df_fs.shape)
display(df_fs.head(3))

df_fs: (180, 351)

,Metadata_Plate,Metadata_Well,Metadata_Control_Type,Metadata_Treatment,Metadata_Concentration,Metadata_Cell_Type,Cells_AreaShape_CentralMoment_0_3,Cells_AreaShape_CentralMoment_1_0,Cells_AreaShape_CentralMoment_1_2,Cells_AreaShape_CentralMoment_2_1,Cells_AreaShape_CentralMoment_2_3,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,Cells_AreaShape_HuMoment_0,Cells_AreaShape_HuMoment_2,Cells_AreaShape_HuMoment_3,Cells_AreaShape_HuMoment_4,Cells_AreaShape_HuMoment_5,Cells_AreaShape_HuMoment_6,Cells_AreaShape_NormalizedMoment_0_2,Cells_AreaShape_NormalizedMoment_0_3,Cells_AreaShape_NormalizedMoment_1_2,Cells_AreaShape_NormalizedMoment_2_0,Cells_AreaShape_NormalizedMoment_2_1,Cells_AreaShape_NormalizedMoment_2_2,Cells_AreaShape_NormalizedMoment_2_3,Cells_AreaShape_NormalizedMoment_3_0,Cells_AreaShape_NormalizedMoment_3_1,Cells_AreaShape_NormalizedMoment_3_2,Cells_AreaShape_NormalizedMoment_3_3,Cells_AreaShape_Perimeter,Cells_AreaShape_Solidity,Cells_AreaShape_Zernike_0_0,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_2_2,Cells_AreaShape_Zernike_3_1,Cells_AreaShape_Zernike_3_3,Cells_AreaShape_Zernike_4_0,Cells_AreaShape_Zernike_4_2,Cells_AreaShape_Zernike_5_1,Cells_AreaShape_Zernike_5_3,Cells_AreaShape_Zernike_6_0,Cells_AreaShape_Zernike_6_2,Cells_AreaShape_Zernike_6_4,Cells_AreaShape_Zernike_6_6,Cells_AreaShape_Zernike_7_1,Cells_AreaShape_Zernike_7_3,Cells_AreaShape_Zernike_7_5,Cells_AreaShape_Zernike_8_0,Cells_AreaShape_Zernike_8_2,Cells_AreaShape_Zernike_8_4,Cells_AreaShape_Zernike_9_1,Cells_AreaShape_Zernike_9_3,Cells_AreaShape_Zernike_9_5,Cells_AreaShape_Zernike_9_7,Cells_AreaShape_Zernike_9_9,Cells_Children_Vesicles_Count,Cells_Granularity_10_AOPI,Cells_Granularity_1_AOGFP,Cells_Granularity_1_AOPI,Cells_Granularity_2_AOPI,Cells_Granularity_3_AOGFP,Cells_Granularity_3_AOPI,Cells_Granularity_5_AOGFP,Cells_Granularity_5_AOPI,Cells_Granularity_6_AOGFP,Cells_Granularity_7_AOGFP,Cells_Granularity_9_AOPI,Cells_Intensity_MassDisplacement_AOGFP,Cells_Intensity_MassDisplacement_AOPI,Cells_Intensity_MinIntensity_AOPI,Cells_Location_MaxIntensity_Y_AOPI,Cells_Mean_Vesicles_AreaShape_BoundingBoxMaximum_X,Cells_Mean_Vesicles_AreaShape_CentralMoment_0_1,Cells_Mean_Vesicles_AreaShape_CentralMoment_0_3,Cells_Mean_Vesicles_AreaShape_CentralMoment_1_0,Cells_Mean_Vesicles_AreaShape_CentralMoment_1_1,Cells_Mean_Vesicles_AreaShape_CentralMoment_1_2,Cells_Mean_Vesicles_AreaShape_CentralMoment_2_1,Cells_Mean_Vesicles_AreaShape_Eccentricity,Cells_Mean_Vesicles_AreaShape_Extent,Cells_Mean_Vesicles_AreaShape_HuMoment_1,Cells_Mean_Vesicles_AreaShape_HuMoment_2,Cells_Mean_Vesicles_AreaShape_InertiaTensor_0_1,Cells_Mean_Vesicles_AreaShape_MedianRadius,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_0_2,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_0_3,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_1_2,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_1_3,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_2_2,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_3_2,Cells_Mean_Vesicles_AreaShape_NormalizedMoment_3_3,Cells_Mean_Vesicles_AreaShape_Orientation,Cells_Mean_Vesicles_AreaShape_Zernike_1_1,Cells_Mean_Vesicles_AreaShape_Zernike_2_0,Cells_Mean_Vesicles_AreaShape_Zernike_2_2,Cells_Mean_Vesicles_AreaShape_Zernike_3_1,...,Nuclei_AreaShape_Zernike_7_5,Nuclei_AreaShape_Zernike_7_7,Nuclei_AreaShape_Zernike_8_0,Nuclei_AreaShape_Zernike_8_2,Nuclei_AreaShape_Zernike_8_4,Nuclei_AreaShape_Zernike_8_6,Nuclei_AreaShape_Zernike_8_8,Nuclei_AreaShape_Zernike_9_1,Nuclei_AreaShape_Zernike_9_3,Nuclei_AreaShape_Zernike_9_5,Nuclei_AreaShape_Zernike_9_7,Nuclei_AreaShape_Zernike_9_9,Nuclei_Correlation_Correlation_AOGFP_AOPI,Nuclei_Correlation_K_AOGFP_AOPI,Nuclei_Correlation_Overlap_AOGFP_AOPI,Nuclei_Correlation_RWC_AOPI_AOGFP,Nuclei_Granularity_10_AOGFP,Nuclei_Granularity_10_AOPI,Nuclei_Granularity_1_AOGFP,Nuclei_Granularity_1_AOPI,Nuclei_Granularity_2_AOGFP,Nuclei_Granularity_2_AOPI,Nuclei_Granularity_3_AOGFP,Nuclei_Granularity_5_AOGFP,Nuclei_Granularity_5_AOPI,Nuclei_Granularity_6_AOGFP,Nuclei_Granularity_6_AOPI,Nuclei_Granularity_7_AOPI,Nuclei_Granularity_8_AOPI,Nuclei_Granularity_9_AOGFP,Nuclei_Granularity_9_AOPI,Nuclei_Intensity_MassDisplacement_AOGFP,Nuclei_Intensity_MassDisplacement_AOPI,Nuclei_Intensity_MinIntensity_AOPI,Nuclei_Intensity_StdIntensityEdge_AOPI,Nuclei_Mean_Nucleoli_AreaShape_BoundingBoxMaximum_X,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_0_1,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_0_3,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_0,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_1,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_2,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_2_1,Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_2_3,Nuclei_Mean_Nucleoli_AreaShape_HuMoment_4,Nuclei_Mean_Nucleoli_AreaShape_HuMoment_6,Nuclei_Mean_Nucleoli_AreaShape_InertiaTensor_1_0,Nuclei_Mean_Nucleoli_AreaShape_MedianRadius,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_0_2,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_0_3,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_1_2,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_1,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_3,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_0,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_2,Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_3,Nuclei_Mean_Nucleoli_AreaShape_Orientation,Nuclei_Mean_Nucleoli_AreaShape_Zernike_0_0,Nuclei_Mean_Nucleoli_AreaShape_Zernike_2_2,Nuclei_Mean_Nucleoli_AreaShape_Zernike_3_1,Nuclei_Mean_Nucleoli_AreaShape_Zernike_3_3,Nuclei_Mean_Nucleoli_AreaShape_Zernike_4_0,Nuclei_Mean_Nucleoli_AreaShape_Zernike_4_4,Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_1,Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_3,Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_5,Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_0,Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_6,Nuclei_Mean_Nucleoli_AreaShape_Zernike_7_7,Nuclei_Mean_Nucleoli_Intensity_MassDisplacement_AOGFP,Nuclei_Mean_Nucleoli_Intensity_MassDisplacement_AOPI,Nuclei_Mean_Nucleoli_Intensity_StdIntensityEdge_AOGFP,Nuclei_Mean_Nucleoli_Intensity_StdIntensityEdge_AOPI,Nuclei_Mean_Nucleoli_Number_Object_Number,Nuclei_Texture_AngularSecondMoment_AOGFP_5_00_256,Nuclei_Texture_AngularSecondMoment_AOPI_5_03_256,Nuclei_Texture_Contrast_AOPI_5_03_256,Nuclei_Texture_Correlation_AOGFP_10_00_256,Nuclei_Texture_Correlation_AOGFP_10_01_256,Nuclei_Texture_Correlation_AOGFP_10_02_256,Nuclei_Texture_Correlation_AOGFP_10_03_256,Nuclei_Texture_Correlation_AOGFP_20_00_256,Nuclei_Texture_Correlation_AOGFP_20_01_256,Nuclei_Texture_Correlation_AOGFP_20_02_256,Nuclei_Texture_Correlation_AOGFP_20_03_256,Nuclei_Texture_Correlation_AOGFP_5_01_256,Nuclei_Texture_Correlation_AOGFP_5_02_256,Nuclei_Texture_Correlation_AOGFP_5_03_256,Nuclei_Texture_Correlation_AOPI_10_00_256,Nuclei_Texture_Correlation_AOPI_10_01_256,Nuclei_Texture_Correlation_AOPI_10_02_256,Nuclei_Texture_Correlation_AOPI_10_03_256,Nuclei_Texture_Correlation_AOPI_20_00_256,Nuclei_Texture_Correlation_AOPI_20_01_256,Nuclei_Texture_Correlation_AOPI_20_02_256,Nuclei_Texture_Correlation_AOPI_20_03_256,Nuclei_Texture_Correlation_AOPI_5_01_256,Nuclei_Texture_Entropy_AOGFP_20_03_256,Nuclei_Texture_InfoMeas1_AOPI_10_01_256,Nuclei_Texture_InfoMeas2_AOGFP_20_02_256,Nuclei_Texture_InfoMeas2_AOPI_10_02_256
0,260221_171841_Plate_1_R1,B02,negcon,Non-treated,0.00000,HUH-7,-0.235600,-0.015277,-0.261603,0.468864,0.252439,-0.914061,-0.436290,0.353525,0.971592,-0.366021,-1.010468,-0.001932,-0.047269,0.163491,-0.000168,-0.988504,-0.334548,-0.459257,-0.116844,0.819155,0.509515,1.285000,1.671730,0.656204,-0.201939,0.285318,-2.607470,0.151978,0.370081,-0.097038,-0.184388,-0.376600,-0.447186,-1.088955,0.351280,-1.350220,-0.954641,-1.570045,2.180831,-0.699939,-0.622769,0.324557,-0.636859,1.004661,-0.355165,0.432883,-0.483694,-0.076445,0.700969,-1.454644,-0.681681,0.250904,-1.169599,-1.694452,-1.533704,-4.414504,1.311141,-1.340060,1.847219,-2.198553,3.269104,-0.832334,4.172191,1.293565,-1.708732,1.786420,-2.030868,1.162199,0.256306,0.584872,0.000000e+00,0.125358,-2.071999e-08,-1.368644,1.020347,0.041404,-2.184085,2.804514,0.971767,0.001574,1.325052,-1.284319,-3.215799,0.675095,0.528840,-0.668154,-2.254779,0.674411,-0.405917,2.081401,0.645495,0.400221,-0.194705,0.846003,...,0.234708,0.573593,-0.264331,-1.860374,1.472635,1.648452,0.598179,-0.736833,0.619548,1.306490,0.451199,-1.752736,3.276142,0.662397,1.903176,-0.246123,-1.190523,-0.029327,-4.220083,-2.297453,5.530441,2.831647,5.661242,4.711776,2.969277,1.981996,2.818523,0.731396,-0.973393,-0.905474,-0.877054,2.219867,-1.039753,0.691639,-0.439054,0.042156,-1.443289e-07,-2.048679,0.000000e+00,-0.218270,-1.171833,1.312589,-0.976029,0.054211,-0.000010,0.672699,3.759399,1.214758,1.084880,0.908016,-0.441314,-2.620828,-1.229475,-0.241067,-1.706982,-1.187357,-1.090865,0.300885,-1.945145,0.876030,-1.284007,-1.204475,-2.013385,-1.641716,-2.244041,-2.013317,-2.498395,-1.562279,3.828096,0.667055,1.387698,1.995693,1.492361,-0.965038,-1.470884,5.773541,-2.084572,-2.893209,-1.318076,-2.350618,-2.038011,-1.863830,-2.730382,-1.387831,-0.326212,0.069900,-0.573196,-1.368866,-3.451374,-2.138542,-3.697605,-4.341777,-4.025551,-5.110445,-4.256101,-0.188595,0.222020,-3.499075,1.166080,2.078383
1,260221_171841_Plate_1_R1,B03,trt,NPPS420,0.00025,HUH-7,2.461245,0.008886,-1.301110,-2.059295,0.059060,-0.231399,-0.852581,0.115131,0.238398,-0.759710,-1.314368,-0.811406,-0.096288,-0.211824,0.000061,-0.682783,2.407200,-0.572502,0.061739,-1.757960,-1.645128,0.173627,0.950190,-0.052391,1.095054,0.237502,-1.273183,-0.193528,0.459584,0.194763,-0.295826,-0.756772,0.272233,-0.050771,-0.659512,-1.468493,0.714701,-1.723813,0.194124,-0.658287,0.020981,1.321463,0.438835,-0.182144,0.252976,-0.389131,-0.110195,-0.426541,0.110462,0.472759,-0.501072,0.425176,-0.391991,-0.904805,2.762288,-4.010661,-0.541758,0.675398,1.722326,-0.250546,1.823203,-0.236942,1.647022,0.850668,0.410907,2.775500,-0.444251,0.332057,-2.711453,1.366682,0.000000e+00,-0.559293,4.519410e-08,-1.043336,-1.787095,0.196058,-0.894296,0.639343,-1.605313,-1.626735,1.001624,0.277700,0.167320,0.113534,-0.371594,-0.605963,-1.121388,0.283039,-0.508541,-1.497173,-0.887533,0.601585,0.728386,-0.568633,...,-3.216288,-0.712355,0.242348,-0.454523,-0.728512,-0.538154,-1.344654,-1.367086,-1.128462,-0.994944,-1.846946,-0.086978,1.383050,0.818033,-0.064760,0.326793,-0.489084,1.869483,-1.001784,-0.601096,4.201922,1.453409,2.184123,0.415998,0.686128,-0.636379,0.048154,-0.306480,-0.752169,-1.565246,0.383136,3.641623,0.916515,0.360109,0.898273,-0.171634,3.256653e-07,-0.102200,-8.881778e-07,-0.875483,-0.754075,-0.303342,0.233006,0.028857,-0.000019,1.073462,1.628365,0.168929,0.025827,-0.054377,-0.454924,-0.262620,0.029358,0.801003,-1.755297,-1.419975,-0.553472,0.225657,0.061329,-0.044505,-0.119048,-0.205130,-2.072271,-0.775362,-0.906638,-0.585418,-1.186171,-0.160130,3.142829,0.373806,0.276255,1.965990,1.034354,-0.147856,-1.180680,4.001130,-1.853820,-2.618611,-0.832557,-0.764614,0.068398,-0.420753,-1.121160,0.480175,-0.836717,-0.223444,-0.494238,-0.246315,-0.790791,-0.300188,-1.009052,-1.171345,-0.435390,-1.815890,-0.746392,0.028325,0.097462,-2.076266,0.200589,1.538462
2,260221_171841_Plate_1_R1,B04,negcon,Lactose,10.00000,HUH-7,-1.284992,0.006299,1.049331,0.000066,-4.113529,0.111401,1.082055,-0.848107,-0.113030,1.692497,2.514290,1.360543,0.666555,2.747705,0.005958,1.864405,-1.107547,0.689148,-0.439304,-0.071910,0.799661,-1.246932,-2.290725,-0.061675,0.927353,-0.694401,0.358846,0.087154,-1.438254,1.196960,-1.551537,-0.661485,3.102665,-1.527285,-0.252957,0.865425,0.375327,-0.634340,-1.092706,-1.321545,-0.126196,0.392234,1.422862,-0.096831,1.544137,0.105527,-0.408869,-0.508548,0.301651,-0.314001,1.122054,-0.867703,1.292127,0.707393,-1.000258,-0.151655,1.132738,-0.719179,-0.335615,-1.053206,-0.331563,-1.216869,-1.498877,-0.562858,-1.345990,1.090091,-0.058025,2.158370,1.713207,-0.247859,-3.400890e-08,-0.578250,4.208713e-08,-1.047252,-1.055322,0.380507,0.029833,-0.535061,-0.607390,0.488349,1.382103,-0.466865,1.025922,-0.657590,0.520520,-1.088336,0.287987,-0.956741,-0.378885,-1.572537,0.382562,-0.072590,-1.348953,1.189583,...,0.514668,0.116589,0.730149,-0.296709,-1.119987,-1.267312,-0.689530,-0.607223,-0.010704,0.088275,0.447790,1.144787,0.660144,0.745560,0.044481,0.532911,-0.774555,-0.198327,-0.576764,-0.410878,2.236718,0.413588,0.851768,-0.599456,0.066542,-0.587086,-0.127708,1.949837,-0.217403,-0.453302,-0.069207,1.584129,0.716706,0.966008,1.479276,2.137895,-1.421085e-06,0.474704,-5.075302e-07,-0.158692,-2.458310,0.317472,0.380410,0.024925,0.000166,0.947403,0.337245,1.274677,0.465128,-0.657391,1.143450,1.073162,-0.165627,-2.790023,-1.043822,-0.775704,-0.874113,1.062802,0.465149,1.141547,0.535520,0.211972,0.438653,-0.071422,0.148370,-0.323007,0.879588,-0.272619,2.290919,0.110391,0.485816,2.234138,1.104630,-0.318978,-1.267362,3.151536,-0.805672,-0.780033,-0.179928,-0.325741,-1.364321,0.484069,-0.376494,0.217065,0.358872,0.526305,-0.376875,0.148903,-0.105505,-0.023261,-0.870916,-0.641700,0.458578,1.457982,-1.308973,0.491161,0.366926,-1.783409,0.339827,1.390652

In [36]:
print("Shape final:", df_fs.shape)
print("Duplicated cols:", df_fs.columns.duplicated().sum())
print("Total NA:", int(df_fs.isna().sum().sum()))
print("Cols with NA:", int((df_fs.isna().sum() > 0).sum()))

Shape final: (180, 351)
Duplicated cols: 0
Total NA: 10
Cols with NA: 10

In [37]:
meta_cols = [c for c in df_fs.columns if c.startswith("Metadata_")]
meta_cols

['Metadata_Plate',
 'Metadata_Well',
 'Metadata_Control_Type',
 'Metadata_Treatment',
 'Metadata_Concentration',
 'Metadata_Cell_Type']

## Passo 9 — Salvar/verificar artefatos finais

In [38]:
def drop_duplicate_and_redundant_cols(df: pd.DataFrame) -> pd.DataFrame:
    df2 = df.copy()

    # 0) Diagnóstico
    dups = df2.columns[df2.columns.duplicated()].tolist()
    if dups:
        print(
            "🔁 Colunas com nome duplicado (antes):",
            dups[:30],
            "..." if len(dups) > 30 else "",
        )

    # 1) Remove colunas vindas do platemap com sufixo _pm
    pm_cols = [c for c in df2.columns if c.endswith("_pm")]
    if pm_cols:
        print(f"🧹 Removendo colunas do PM (sufixo _pm): {len(pm_cols)}")
        df2 = df2.drop(columns=pm_cols, errors="ignore")

    # 2) Prefere Metadata_* às versões cruas
    prefer_meta_pairs = [
        ("Treatment", "Metadata_Treatment"),
        ("Concentration", "Metadata_Concentration"),
        ("Control_Type", "Metadata_Control_Type"),
    ]
    to_drop = []
    for raw, meta in prefer_meta_pairs:
        if raw in df2.columns and meta in df2.columns:
            to_drop.append(raw)

    if to_drop:
        print(f"🧹 Removendo versões cruas (preferindo Metadata_*): {to_drop}")
        df2 = df2.drop(columns=to_drop, errors="ignore")

    # 3) Remove nomes exatamente duplicados, mantendo a 1ª ocorrência
    df2 = df2.loc[:, ~df2.columns.duplicated(keep="first")]

    # 4) Checagem final
    still_dup = df2.columns.duplicated().any()
    print("✅ Duplicadas restantes?", still_dup)

    return df2

In [39]:
# nomes claros
df_perwell_raw = df_agg.copy()
df_perwell_norm = df_norm.copy()
df_perwell_norm_fs = df_fs.copy()

# limpa colunas duplicadas/redundantes antes de salvar
df_perwell_raw = drop_duplicate_and_redundant_cols(df_perwell_raw)
df_perwell_norm = drop_duplicate_and_redundant_cols(df_perwell_norm)
df_perwell_norm_fs = drop_duplicate_and_redundant_cols(df_perwell_norm_fs)

# opcional: imputação leve no artefato final
meta_cols = [c for c in df_perwell_norm_fs.columns if c.startswith("Metadata_")]
numeric_feature_cols = df_perwell_norm_fs.select_dtypes(
    include="number"
).columns.tolist()

df_perwell_norm_fs[numeric_feature_cols] = df_perwell_norm_fs[
    numeric_feature_cols
].apply(lambda s: s.fillna(s.median()))

# salva artefatos
CACHE_DIR.mkdir(parents=True, exist_ok=True)
PROFILES_OUT_DIR.mkdir(parents=True, exist_ok=True)

df_perwell_raw.to_parquet(CACHE_DIR / "per_well_aggregated.parquet", index=False)
df_perwell_norm.to_parquet(CACHE_DIR / "per_well_normalized.parquet", index=False)
df_perwell_norm_fs.to_parquet(
    PROFILES_OUT_DIR / "per_well_features_selected.parquet",
    index=False,
)

print("Arquivos salvos em:")
print(" -", (CACHE_DIR / "per_well_aggregated.parquet").resolve())
print(" -", (CACHE_DIR / "per_well_normalized.parquet").resolve())
print(" -", (PROFILES_OUT_DIR / "per_well_features_selected.parquet").resolve())

print(
    "Shapes:",
    "raw",
    df_perwell_raw.shape,
    "| norm",
    df_perwell_norm.shape,
    "| norm+fs",
    df_perwell_norm_fs.shape,
)

✅ Duplicadas restantes? False
✅ Duplicadas restantes? False
✅ Duplicadas restantes? False
Arquivos salvos em:
 - /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/per_well_aggregated.parquet
 - /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/cache/per_well_normalized.parquet
 - /Users/marcelobispojesus/Documents/dev/camila/lcp-nanoplastics-polystyrene-huh7/workspace/profiles/2026_04_Huh7_NPPS_24h/outputs/per_well_features_selected.parquet
Shapes: raw (180, 1813) | norm (180, 1813) | norm+fs (180, 351)

In [40]:
print("Shape:", df_perwell_norm_fs.shape)
print("Duplicated cols:", df_perwell_norm_fs.columns.duplicated().sum())
print("Total NA:", int(df_perwell_norm_fs.isna().sum().sum()))
print(
    "Non-numeric cols:",
    df_perwell_norm_fs.select_dtypes(exclude="number").columns.tolist(),
)

Shape: (180, 351)
Duplicated cols: 0
Total NA: 0
Non-numeric cols: ['Metadata_Plate', 'Metadata_Well', 'Metadata_Control_Type', 'Metadata_Treatment', 'Metadata_Cell_Type']

In [41]:
[c for c in df_perwell_norm_fs.columns if c.startswith("Metadata_")]

['Metadata_Plate',
 'Metadata_Well',
 'Metadata_Control_Type',
 'Metadata_Treatment',
 'Metadata_Concentration',
 'Metadata_Cell_Type']